apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer-service
  template:
    metadata:
      labels:
        app: kafka-consumer-service
    spec:
      containers:
        - name: kafka-consumer-service
          image: kafka-consumer-service:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-consumer-service
spec:
  type: ClusterIP
  selector:
    app: kafka-consumer-service
  ports:
    - port: 8083
      targetPort: 8083
