apiVersion: v1
kind: Service
metadata:
  name: k8s-demo-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: k8s-demo-service
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
