server:
  port: 8082

spring:
  application:
    name: kafka-producer-service

  kafka:
    bootstrap-servers: kafka.default.svc.cluster.local:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
